### ISSUE TITLE
About NumPy

### ISSUE THREAD

**Issue by MinsGoing** [igor-epam/co2_tracker#8]
When I use PythonFMU, I encounter Numpy related issues and I need your help to solve them.
1.py code
```
from pythonfmu.fmi2slave import Fmi2Slave, Fmi2Causality, Fmi2Variability, Real, Boolean, Integer
import numpy as np
class NPTest(Fmi2Slave):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.a = 0.0
        self.register_variable(Real("a", causality=Fmi2Causality.input))
        self.b = 0.0
        self.register_variable(Real("b", causality=Fmi2Causality.input))
        self.out = 0
        self.register_variable(Integer("out", causality=Fmi2Causality.output))

    def do_step(self, current_time, step_size):

        self.out = self.a + self.b * np.random.rand()
        return True
```
2.When I execute in Matlab, the first time it runs normally, the second time it reports an error:
# Debug Logging enabled for block 'addpython/FMU'
Log from FMU: [category:, status:fmi2Fatal] Fatal py exception encountered: [ctor] PyImport_ImportModule
SystemError('C:\\A\\34\\s\\Objects\\structseq.c:398: bad argument to internal function')

**Do you have any good solutions?**

**Comment by zefir-o** [comment]
@MinsGoing, you reported to the wrong repo, I think, you are talking about PythonFMU.

**Comment by MinsGoing** [comment]
> @MinsGoing, you reported to the wrong repo, I think, you are talking about PythonFMU.

Yes，I'm sorry, I couldn't find any other way to contact you. Therefore, I have found your repository to consult with you.I couldn't find a solution in the PythonFMU issue.

**Comment by zefir-o** [comment]
Ok, looking into the issue.
